// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220622222925_Pacienti")]
    partial class Pacienti
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("Domain.Medikamentet", b =>
                {
                    b.Property<Guid>("MedikamentetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Doza")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emri")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecetaMjekesore")
                        .HasColumnType("TEXT");

                    b.HasKey("MedikamentetId");

                    b.ToTable("Medicaments");
                });

            modelBuilder.Entity("Domain.Pacienti", b =>
                {
                    b.Property<Guid>("PacientiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datelindja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emri")
                        .HasColumnType("TEXT");

                    b.Property<char>("Gjinia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mbiemri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medikamentet")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mosha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Qyteti")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shteti")
                        .HasColumnType("TEXT");

                    b.HasKey("PacientiId");

                    b.ToTable("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
